### ISSUE TITLE
[REFACT] Use URI based routing as state for dialogs

### ISSUE THREAD

**Issue by Krr0ptioN** [khodedawsh/marzneshin#192]
## Description

- This refactor enables developers to have more controll over the user flow by redirecting the user to a specific section of dashboard anywhere in the dashboard.

### Tasks 
- [x] Adapt users page dialog and interactions
   - [x] Create user
   - [x] Edit user
   - [x] View users (settings dialog)
   - [x] Delete user
   - [ ] Error Component routing
   - [ ] Pre-fetching data in dialog component
- [x] Adapt nodes page dialog and interactions
   - [x] Create node
   - [x] Edit node
   - [x] View nodes (settings dialog)
   - [x] Delete node
   - [ ] Error Component routing
   - [ ] Pre-fetching data in dialog component
- [x] Adapt hosts page dialog and interactions
   - [x] Create host
   - [x] Edit host
   - [x] View hosts (settings dialog)
   - [x] Delete host
   - [ ] Error Component routing
   - [ ] Pre-fetching data in dialog component
- [x] Adapt services page dialog and interactions
   - [x] Create service
   - [x] Edit service
   - [x] View services (settings dialog)
   - [x] Delete service
   - [ ] Error Component routing
   - [ ] Pre-fetching data in dialog component
