### ISSUE TITLE
[FEAT] Basic Role based UI adminstration dashboard for sudo and non-sudo admin

### ISSUE THREAD

**Issue by Krr0ptioN** [khodedawsh/marzneshin#373]
## Description

This issue requires the UI to support conditional display and access to certain part of UI for non-sudo admin.

### User Interface Specification
- Non-sudo admin is only allowed to access Users page and home page.
- Sidebar must hide the Hosts, Nodes, Services, and settings page
- The router must reject user access to those correlating address and routes. Non-sudo admin should be redirected to 404 page.

### Technical Interface Specification
- is-sudo property must be included in JWT body.

### Tasks

- [x] is-sudo property in admins route and JWT token response
- [ ] Hiding side bar items such as Hosts, Service, Nodes, Settings
- [ ] Router middleware and restriction policy to reject non-sudo admin access to `/hosts`, `/services`, `/nodes`, `/settings`.

### Related Tasks
- #73 
- #75
