### ISSUE TITLE
[FEAT] Edit services that the user is apart of in user dialog

### ISSUE THREAD

**Issue by Krr0ptioN** [khodedawsh/Marzneshin#5]
## Description

Implement the ability for admin to edit services that the user is a part of, within the user dialog.

### UI Specification

- Already joined services by user must be pre-selected and highlighted and prepared to be deselected if the admin aims to
- Allow the user to add or remove services from their profile.

### Tasks

- [X] Users can access the "Edit Services" feature from the user dialog.
- [ ] The user can see a list of their current services.
- [ ] The user can successfully add or remove services.
- [ ] Changes made to services are reflected in the user's profile.
