### ISSUE TITLE
[EPIC] As Admin, I want to access and manage the services, users, and other objects in sperate page while I can access each page through a sidebar

### ISSUE THREAD

**Issue by Krr0ptioN** [khodedawsh/Marzneshin#6]
## Description

Implement admin functionality to access and manage services, users, and other objects through separate pages. Additionally, provide a sidebar for easy navigation between these pages.

### UI Specification

- Create separate pages for managing services, users, and other objects.
- Design a sidebar for easy navigation with links to each page (services, users, etc.).
- Each page, contain a table to view and modify the existing related object (e.g. Users page contain a table to control and update the users)

### Technical Specification

- Implement routing to handle navigation between the different admin pages.
- Create service management in state zustand has to be updated

### Tasks
- [x] #14
    - [x] Design and implement a sidebar component for navigation.
    - [x] Move the existing user management components from Home page to User Management page.
    - [x] Create separate pages for service, user, and other object management.
- [x] #11
- [x] #41 
- [x] #12
- [x] #13
- [x] #51

### Bugs
- [x] #19
- [x] #20
- [x] #24 
- [x] #26 
- [x] #22 
- [ ] #21

**Comment by Krr0ptioN** [comment]
We should split the `useDashboard` context for statement to more specific and less cluttered state manager.

### Problem
- The existing global statement does not follow single responsibility principle, because we have more pages compared to previous **Marzban**.

### Solution
- [ ] Separate State Management for Services
- [ ] Separate State Management for Users
- [ ] Separate State Management for Nodes
- [ ] Separate State Management for Host
- [ ] Separate State Management for Dashboard
